import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("./ai-client", () => ({
  streamAIText: vi.fn(),
}));

import { streamAIText } from "./ai-client";
import {
  buildTranslationChunks,
  buildTranslationSystemPrompt,
  buildTranslationUserPrompt,
  translateTranscriptChunk,
  validateTranslationLine,
  TranslationFormatError,
} from "./transcript-translation";
import type { Transcript, TranscriptSegment } from "../content/transcript";

const streamAITextMock = vi.mocked(streamAIText);

function segment(text: string, start: number = 0, duration: number = 1): TranscriptSegment {
  return { start, duration, text };
}

function transcript(segments: TranscriptSegment[]): Transcript {
  return { languageCode: "en", isAutoGenerated: true, segments };
}

function tokenStream(...tokens: string[]): AsyncGenerator<string> {
  return (async function* () {
    for (const token of tokens) yield token;
  })();
}

function failingStream(error: Error): AsyncGenerator<string> {
  return (async function* () {
    throw error;
  })();
}

describe("buildTranslationChunks", () => {
  it("covers all source segments exactly once", () => {
    const segments = [
      segment("aaaa", 0),
      segment("bbbb", 1),
      segment("cccc", 2),
      segment("dddd", 3),
    ];
    const chunks = buildTranslationChunks(segments, 30);

    expect(chunks.map(({ targetStart, targetEnd }) => [targetStart, targetEnd]))
      .toEqual([[0, 0], [1, 1], [2, 2], [3, 3]]);
    expect(chunks[1].contextStart).toBe(0);
    expect(chunks[1].contextEnd).toBe(3);
  });

  it("returns no chunks for an empty transcript", () => {
    expect(buildTranslationChunks([])).toEqual([]);
  });

  it("assigns stable ids and never splits an oversized caption", () => {
    const segments = [
      segment("a".repeat(20), 0),
      segment("b".repeat(200), 1),
      segment("c".repeat(20), 2),
    ];
    const chunks = buildTranslationChunks(segments, 60);

    expect(chunks.map((chunk) => chunk.id)).toEqual([0, 1, 2]);
    expect(chunks.map(({ targetStart, targetEnd }) => [targetStart, targetEnd]))
      .toEqual([[0, 0], [1, 1], [2, 2]]);
  });

  it("looks ahead to finish a sentence near the character boundary", () => {
    const segments = [
      segment("unfinished fragment", 0),
      segment("ends here.", 1),
      segment("next fragment", 2),
    ];

    expect(buildTranslationChunks(segments, 45)[0]).toMatchObject({
      targetStart: 0,
      targetEnd: 1,
    });
  });
});

describe("timestamped translation prompts", () => {
  it("asks for natural timed sentences without source IDs", () => {
    const source = transcript([
      segment("context", 1905, 3),
      segment("And now with", 1908, 3),
      segment("step two completed.", 1911, 3),
      segment("after", 1914, 3),
    ]);
    const chunk = {
      id: 0,
      targetStart: 1,
      targetEnd: 2,
      contextStart: 0,
      contextEnd: 3,
    };
    const systemPrompt = buildTranslationSystemPrompt("zh-CN");
    const userPrompt = buildTranslationUserPrompt(source, chunk);

    expect(systemPrompt).toContain("natural complete sentences");
    expect(systemPrompt).toContain('{"type":"complete"}');
    expect(userPrompt).toContain('[31:48] "And now with"');
    expect(userPrompt).toContain("CONTEXT BEFORE — DO NOT TRANSLATE");
    expect(userPrompt).toContain("Allowed TARGET startTime range: 31:48-31:53 inclusive");
    expect(`${systemPrompt}\n${userPrompt}`).not.toContain("sourceStartId");
    expect(`${systemPrompt}\n${userPrompt}`).not.toContain("sourceEndId");
  });
});

describe("validateTranslationLine", () => {
  it("accepts estimated and repeated in-range timestamps", () => {
    expect(validateTranslationLine(
      '{"type":"caption","startTime":"31:49","translatedText":"译文"}',
      1908,
      1917,
      1909,
    )).toEqual({ type: "caption", start: 1909, translatedText: "译文" });
    expect(validateTranslationLine(
      '{"type":"complete"}',
      1908,
      1917,
      1909,
    )).toEqual({ type: "complete" });
  });

  it("accepts hour-format timestamps", () => {
    expect(validateTranslationLine(
      '{"type":"caption","startTime":"1:02:03","translatedText":"长视频译文"}',
      3720,
      3740,
      null,
    )).toEqual({ type: "caption", start: 3723, translatedText: "长视频译文" });
  });

  it("rejects out-of-range and decreasing timestamps", () => {
    expect(() => validateTranslationLine(
      '{"type":"caption","startTime":"31:47","translatedText":"越界"}',
      1908,
      1917,
      null,
    )).toThrow(TranslationFormatError);
    expect(() => validateTranslationLine(
      '{"type":"caption","startTime":"31:50","translatedText":"倒序"}',
      1908,
      1917,
      1911,
    )).toThrow(TranslationFormatError);
  });

  it("rejects malformed records and empty translations", () => {
    expect(() => validateTranslationLine("not json", 0, 10, null))
      .toThrow(TranslationFormatError);
    expect(() => validateTranslationLine(
      '{"type":"caption","startTime":"0:01","translatedText":""}',
      0,
      10,
      null,
    )).toThrow(TranslationFormatError);
  });
});

describe("translateTranscriptChunk", () => {
  beforeEach(() => {
    streamAITextMock.mockReset();
  });

  it("maps naturally resegmented sentences back to estimated timestamps", async () => {
    const source = transcript([
      segment("And now with", 1908, 3),
      segment("step two completed, I was", 1911, 3),
      segment("almost done.", 1914, 3),
    ]);
    const chunk = buildTranslationChunks(source.segments)[0];
    streamAITextMock.mockImplementation(() => tokenStream(
      '{"type":"caption","startTime":"31:49","translatedText":"现在，第二步已经完成，"}\n',
      '{"type":"caption","startTime":"31:54","translatedText":"我就快完成了。"}\n',
      '{"type":"complete"}\n',
    ));

    await expect(translateTranscriptChunk(source, chunk, "zh-CN")).resolves.toEqual([
      { start: 1909, duration: 5, text: "现在，第二步已经完成，" },
      { start: 1914, duration: 3, text: "我就快完成了。" },
    ]);
    expect(streamAITextMock).toHaveBeenCalledTimes(1);
    expect(streamAITextMock.mock.calls[0][1]).toContain("TRANSLATE ALL OF THIS");
  });

  it("retries a missing completion marker with the exact validation reason", async () => {
    const source = transcript([segment("hello world", 0, 2)]);
    const chunk = buildTranslationChunks(source.segments)[0];
    streamAITextMock
      .mockImplementationOnce(() => tokenStream(
        '{"type":"caption","startTime":"0:00","translatedText":"你好，世界。"}\n',
      ))
      .mockImplementationOnce(() => tokenStream(
        '{"type":"caption","startTime":"0:00","translatedText":"你好，世界。"}\n',
        '{"type":"complete"}\n',
      ));

    const progress: Array<{ length: number; repairing: boolean }> = [];
    await expect(translateTranscriptChunk(
      source,
      chunk,
      "zh-CN",
      (partial, repairing) => progress.push({ length: partial.length, repairing }),
    )).resolves.toHaveLength(1);

    expect(streamAITextMock).toHaveBeenCalledTimes(2);
    expect(streamAITextMock.mock.calls[1][1]).toContain("failed validation");
    expect(progress).toContainEqual({ length: 0, repairing: true });
  });

  it("splits the source range after two format failures", async () => {
    const source = transcript([
      segment("zero", 0, 2),
      segment("one", 2, 2),
      segment("two", 4, 2),
      segment("three", 6, 2),
    ]);
    const chunk = buildTranslationChunks(source.segments)[0];
    const outputs = [
      "not json\n",
      "still not json\n",
      '{"type":"caption","startTime":"0:00","translatedText":"前半。"}\n{"type":"complete"}\n',
      '{"type":"caption","startTime":"0:04","translatedText":"后半。"}\n{"type":"complete"}\n',
    ];
    streamAITextMock.mockImplementation(() => tokenStream(outputs.shift()!));

    await expect(translateTranscriptChunk(source, chunk, "zh-CN")).resolves.toEqual([
      { start: 0, duration: 4, text: "前半。" },
      { start: 4, duration: 4, text: "后半。" },
    ]);
    expect(streamAITextMock).toHaveBeenCalledTimes(4);
  });

  it("does not split provider or network errors", async () => {
    const source = transcript([
      segment("zero", 0, 2),
      segment("one", 2, 2),
    ]);
    const chunk = buildTranslationChunks(source.segments)[0];
    streamAITextMock.mockImplementation(() => failingStream(new Error("network failed")));

    await expect(translateTranscriptChunk(source, chunk, "zh-CN"))
      .rejects.toThrow("network failed");
    expect(streamAITextMock).toHaveBeenCalledTimes(1);
  });
});
