import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("./ai-client", () => ({
  streamAIText: vi.fn(),
}));

import { streamAIText } from "./ai-client";
import {
  buildTranslationChunks,
  buildTranslationSystemPrompt,
  buildTranslationUserPrompt,
  translateTranscriptChunk,
  validateTranslationLine,
  TranslationFormatError,
} from "./transcript-translation";
import type { Transcript, TranscriptSegment } from "../content/transcript";

const streamAITextMock = vi.mocked(streamAIText);

function segment(
  text: string,
  start: number = 0,
  duration: number = 1,
  sourceStartId?: number,
  sourceEndId?: number,
): TranscriptSegment {
  return { start, duration, text, sourceStartId, sourceEndId };
}

function transcript(segments: TranscriptSegment[]): Transcript {
  return { languageCode: "en", isAutoGenerated: true, segments };
}

function tokenStream(...tokens: string[]): AsyncGenerator<string> {
  return (async function* () {
    for (const token of tokens) yield token;
  })();
}

function failingStream(error: Error): AsyncGenerator<string> {
  return (async function* () {
    throw error;
  })();
}

describe("buildTranslationChunks", () => {
  it("covers every aligned cue once and caps stable sections by duration", () => {
    const segments = [
      segment("a", 0, 20),
      segment("b", 20, 20),
      segment("c", 40, 20),
      segment("d", 60, 20),
    ];
    const chunks = buildTranslationChunks(segments, 4_000, 60);

    expect(chunks.map(({ targetStart, targetEnd }) => [targetStart, targetEnd]))
      .toEqual([[0, 2], [3, 3]]);
    expect(chunks.map((chunk) => chunk.id)).toEqual([0, 1]);
  });

  it("returns no chunks for an empty transcript", () => {
    expect(buildTranslationChunks([])).toEqual([]);
  });

  it("never splits an oversized cue", () => {
    const chunks = buildTranslationChunks([
      segment("a".repeat(200), 0, 90),
      segment("next", 90, 2),
    ], 60, 60);
    expect(chunks.map(({ targetStart, targetEnd }) => [targetStart, targetEnd]))
      .toEqual([[0, 0], [1, 1]]);
  });
});

describe("aligned translation prompts", () => {
  it("requires one immutable translation per target cue", () => {
    const source = transcript([
      segment("context", 1905, 3),
      segment("And now with", 1908, 3),
      segment("step two completed.", 1911, 3),
      segment("after", 1914, 3),
    ]);
    const chunk = {
      id: 0,
      targetStart: 1,
      targetEnd: 2,
      contextStart: 0,
      contextEnd: 3,
    };
    const systemPrompt = buildTranslationSystemPrompt("zh-CN");
    const userPrompt = buildTranslationUserPrompt(source, chunk);

    expect(systemPrompt).toContain("Never merge, split, skip, duplicate, or reorder cues");
    expect(systemPrompt).toContain("Do not return timestamps");
    expect(systemPrompt).toContain('{"type":"caption","cueId":12');
    expect(userPrompt).toContain('"cueId":1,"startTime":"31:48","endTime":"31:51"');
    expect(userPrompt).toContain("CONTEXT BEFORE — DO NOT TRANSLATE");
    expect(userPrompt).toContain("TARGET cue IDs: 1-2 inclusive");
  });
});

describe("validateTranslationLine", () => {
  it("accepts only the next expected cue ID", () => {
    expect(validateTranslationLine(
      '{"type":"caption","cueId":4,"translatedText":"译文"}',
      4,
      8,
    )).toEqual({ type: "caption", cueId: 4, translatedText: "译文" });
    expect(validateTranslationLine('{"type":"complete"}', 9, 8))
      .toEqual({ type: "complete" });
  });

  it("rejects missing, duplicate, out-of-order, timestamped, and empty records", () => {
    expect(() => validateTranslationLine("not json", 0, 1)).toThrow(TranslationFormatError);
    expect(() => validateTranslationLine(
      '{"type":"caption","cueId":1,"translatedText":"skip"}',
      0,
      1,
    )).toThrow(TranslationFormatError);
    expect(() => validateTranslationLine(
      '{"type":"caption","cueId":0,"startTime":"0:01","translatedText":"timed"}',
      0,
      1,
    )).toThrow(TranslationFormatError);
    expect(() => validateTranslationLine(
      '{"type":"caption","cueId":0,"translatedText":""}',
      0,
      1,
    )).toThrow(TranslationFormatError);
  });
});

describe("translateTranscriptChunk", () => {
  beforeEach(() => {
    streamAITextMock.mockReset();
  });

  afterEach(() => {
    vi.useRealTimers();
    vi.restoreAllMocks();
  });

  it("keeps local cue timing and original source ranges", async () => {
    const source = transcript([
      segment("had attempted it and not finished because it's a brutal event.", 178, 6, 20, 22),
      segment("One of the best things about doing the race is afterwards you finish.", 184, 6, 23, 24),
    ]);
    const chunk = buildTranslationChunks(source.segments)[0];
    streamAITextMock.mockImplementation(() => tokenStream(
      '{"type":"caption","cueId":0,"translatedText":"许多人尝试过却未能完成，因为这是一场残酷的赛事。"}\n',
      '{"type":"caption","cueId":1,"translatedText":"参加比赛最棒的事情之一就是最终完赛。"}\n',
      '{"type":"complete"}\n',
    ));

    await expect(translateTranscriptChunk(source, chunk, "zh-CN")).resolves.toEqual([
      {
        cueId: 0,
        sourceStartId: 20,
        sourceEndId: 22,
        start: 178,
        duration: 6,
        text: "许多人尝试过却未能完成，因为这是一场残酷的赛事。",
      },
      {
        cueId: 1,
        sourceStartId: 23,
        sourceEndId: 24,
        start: 184,
        duration: 6,
        text: "参加比赛最棒的事情之一就是最终完赛。",
      },
    ]);
  });

  it("retries a missing completion marker with the validation reason", async () => {
    const source = transcript([segment("hello world", 0, 2)]);
    const chunk = buildTranslationChunks(source.segments)[0];
    streamAITextMock
      .mockImplementationOnce(() => tokenStream(
        '{"type":"caption","cueId":0,"translatedText":"你好，世界。"}\n',
      ))
      .mockImplementationOnce(() => tokenStream(
        '{"type":"caption","cueId":0,"translatedText":"你好，世界。"}\n',
        '{"type":"complete"}\n',
      ));

    const progress: Array<{ length: number; repairing: boolean }> = [];
    await expect(translateTranscriptChunk(
      source,
      chunk,
      "zh-CN",
      (partial, repairing) => progress.push({ length: partial.length, repairing }),
    )).resolves.toHaveLength(1);

    expect(streamAITextMock).toHaveBeenCalledTimes(2);
    expect(streamAITextMock.mock.calls[1][1]).toContain("failed validation");
    expect(progress).toContainEqual({ length: 0, repairing: true });
  });

  it("splits a range after repeated format failures without merging cues", async () => {
    const source = transcript([
      segment("zero", 0, 2),
      segment("one", 2, 2),
      segment("two", 4, 2),
      segment("three", 6, 2),
    ]);
    const chunk = buildTranslationChunks(source.segments)[0];
    const outputs = [
      "not json\n",
      "still not json\n",
      '{"type":"caption","cueId":0,"translatedText":"零"}\n' +
        '{"type":"caption","cueId":1,"translatedText":"一"}\n' +
        '{"type":"complete"}\n',
      '{"type":"caption","cueId":2,"translatedText":"二"}\n' +
        '{"type":"caption","cueId":3,"translatedText":"三"}\n' +
        '{"type":"complete"}\n',
    ];
    streamAITextMock.mockImplementation(() => tokenStream(outputs.shift()!));

    await expect(translateTranscriptChunk(source, chunk, "zh-CN"))
      .resolves.toMatchObject([
        { cueId: 0, start: 0, duration: 2, text: "零" },
        { cueId: 1, start: 2, duration: 2, text: "一" },
        { cueId: 2, start: 4, duration: 2, text: "二" },
        { cueId: 3, start: 6, duration: 2, text: "三" },
      ]);
    expect(streamAITextMock).toHaveBeenCalledTimes(4);
  });

  it("retries a failed network batch without splitting cues", async () => {
    vi.useFakeTimers();
    vi.spyOn(console, "debug").mockImplementation(() => {});
    const source = transcript([segment("zero", 0, 2), segment("one", 2, 2)]);
    const chunk = buildTranslationChunks(source.segments)[0];
    streamAITextMock
      .mockImplementationOnce(() => failingStream(new Error("Failed to fetch")))
      .mockImplementationOnce(() => tokenStream(
        '{"type":"caption","cueId":0,"translatedText":"零"}\n',
        '{"type":"caption","cueId":1,"translatedText":"一"}\n',
        '{"type":"complete"}\n',
      ));

    const result = translateTranscriptChunk(source, chunk, "zh-CN");
    await vi.runAllTimersAsync();
    await expect(result).resolves.toMatchObject([{ cueId: 0 }, { cueId: 1 }]);
    expect(streamAITextMock).toHaveBeenCalledTimes(2);
  });

  it("does not split an exhausted network error into smaller requests", async () => {
    vi.useFakeTimers();
    vi.spyOn(console, "debug").mockImplementation(() => {});
    const source = transcript([segment("zero", 0, 2), segment("one", 2, 2)]);
    const chunk = buildTranslationChunks(source.segments)[0];
    streamAITextMock.mockImplementation(() => failingStream(new Error("network failed")));

    const result = translateTranscriptChunk(source, chunk, "zh-CN");
    const assertion = expect(result).rejects.toThrow("network failed");
    await vi.runAllTimersAsync();
    await assertion;
    expect(streamAITextMock).toHaveBeenCalledTimes(2);
  });
});
