/**
 * 字幕拦截器。
 *
 * 内容脚本运行在 ISOLATED world（以正常加载 CRXJS bundle），
 * manifest 在 document_start 将独立脚本注入 MAIN world，
 * 本模块只负责接收捕获结果并维护小型内存缓存。
 *
 * 主世界的拦截器通过 DOM CustomEvent 把捕获的字幕数据传回内容脚本。
 *
 * 该缓存只是无等待的快速路径；主动获取由 InnerTube/直接 fetch 完成。
 */

import type {
  Transcript,
  TranscriptSegment,
  TranscriptTimingMarker,
} from "../transcript";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
interface CaptionCacheEntry {
  transcript: Transcript;
  timestamp: number;
}

// ---------------------------------------------------------------------------
// Cache (ISOLATED world)
// ---------------------------------------------------------------------------
const captionCache = new Map<string, CaptionCacheEntry>();
const CAPTION_CACHE_TTL_MS = 5 * 60 * 1000;
const MAX_CAPTION_CACHE_ENTRIES = 12;
const MAX_CAPTURED_CAPTION_CHARS = 5_000_000;

export function parseJson3Captions(
  raw: string,
  languageCode: string = "unknown",
  isAutoGenerated: boolean = true,
): Transcript | null {
  let data: Record<string, unknown>;
  try { data = JSON.parse(raw); } catch { return null; }

  const events = data?.events;
  if (!events || !Array.isArray(events)) return null;

  const segments: TranscriptSegment[] = [];
  for (const ev of events as Array<Record<string, unknown>>) {
    if (!Array.isArray(ev.segs)) continue;
    const startMs = Number(ev.tStartMs);
    const durationMs = Number(ev.dDurationMs);
    if (!Number.isFinite(startMs) || startMs < 0 || !Number.isFinite(durationMs) || durationMs < 0) {
      continue;
    }
    const runs = (ev.segs as unknown[]).map((seg) => {
      const value = seg && typeof seg === "object" ? seg as Record<string, unknown> : {};
      return {
        text: typeof value.utf8 === "string" ? value.utf8 : "",
        offsetMs: Number(value.tOffsetMs),
      };
    });
    const rawText = runs.map(({ text }) => text).join("");
    const normalize = (text: string) => text
      .split("\n")
      .map((line) => line.trim().replace(/\s+/g, " "))
      .filter(Boolean)
      .join("\n");
    const text = normalize(rawText);
    if (text) {
      const timingMarkers: TranscriptTimingMarker[] = [];
      let rawOffset = 0;
      for (const run of runs) {
        const runText = normalize(run.text);
        if (runText && Number.isFinite(run.offsetMs) && run.offsetMs >= 0) {
          const approximateOffset = normalize(rawText.slice(0, rawOffset)).length;
          const foundOffset = text.indexOf(runText, Math.max(0, approximateOffset - 1));
          const offset = foundOffset >= 0 ? foundOffset : Math.min(text.length - 1, approximateOffset);
          const start = (startMs + run.offsetMs) / 1000;
          const previous = timingMarkers.at(-1);
          if (!previous || previous.offset !== offset || previous.start !== start) {
            timingMarkers.push({ offset, start });
          }
        }
        rawOffset += run.text.length;
      }
      segments.push({
        start: startMs / 1000,
        duration: durationMs / 1000,
        text,
        ...(timingMarkers.length ? { timingMarkers } : {}),
      });
    }
  }
  if (!segments.length) return null;
  return { languageCode, isAutoGenerated, segments };
}

function extractLangFromURL(url: string): string {
  try { return new URL(url).searchParams.get("lang") || "unknown"; }
  catch { const m = url.match(/[?&]lang=([^&]+)/); return m ? m[1] : "unknown"; }
}

/** YouTube's `tlang` response contains translated text and must never become our source track. */
export function isTranslatedCaptionURL(url: string): boolean {
  try { return new URL(url).searchParams.has("tlang"); }
  catch { return /[?&]tlang=/.test(url); }
}

function extractVideoIdFromURL(url: string): string {
  try { return new URL(url).searchParams.get("v") || ""; }
  catch { const m = url.match(/[?&]v=([^&]+)/); return m ? m[1] : ""; }
}

function makeCacheKey(videoId: string, languageCode: string): string {
  return `${videoId}:${languageCode}`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

let installed = false;

/** 注册 MAIN world 捕获事件监听器（幂等）。 */
export function initCaptionInterceptor(): void {
  if (installed) return;
  installed = true;

  // Listen for captured captions from MAIN world
  // (DOM CustomEvents on document DO cross the isolated-world boundary)
  document.addEventListener('vas-caption-captured', ((e: Event) => {
    const detail = (e as CustomEvent).detail as Record<string, unknown> | undefined;
    if (
      typeof detail?.url !== "string" ||
      typeof detail.text !== "string" ||
      !detail.text ||
      detail.text.length > MAX_CAPTURED_CAPTION_CHARS
    ) return;

    const url = detail.url;
    const raw = detail.text;
    if (isTranslatedCaptionURL(url)) return;
    try {
      const parsedUrl = new URL(url);
      const isYouTubeHost = parsedUrl.hostname === "youtube.com" ||
        parsedUrl.hostname.endsWith(".youtube.com");
      if (!isYouTubeHost || !parsedUrl.pathname.includes("/api/timedtext")) {
        return;
      }
    } catch {
      return;
    }
    const lang = extractLangFromURL(url);
    const videoId = extractVideoIdFromURL(url);
    if (!videoId) return;

    const key = makeCacheKey(videoId, lang);
    const existing = captionCache.get(key);
    if (existing && existing.timestamp > Date.now() - 30000) return;

    const transcript = parseJson3Captions(raw, lang);
    if (!transcript) return;

    captionCache.set(key, { transcript, timestamp: Date.now() });
    while (captionCache.size > MAX_CAPTION_CACHE_ENTRIES) {
      const oldestKey = [...captionCache.entries()]
        .sort((a, b) => a[1].timestamp - b[1].timestamp)[0]?.[0];
      if (!oldestKey) break;
      captionCache.delete(oldestKey);
    }
    console.log(`[vas] Cached captions: video=${videoId} lang=${lang} segments=${transcript.segments.length}`);
  }) as EventListener);
}

// ---------------------------------------------------------------------------
// Read intercepted timedtext without waiting or changing player state
// ---------------------------------------------------------------------------

/** Check caption cache for a matching entry. */
export function getCachedCaptionedText(
  videoId: string,
  preferredLangs: string[],
): Transcript | null {
  const cutoff = Date.now() - CAPTION_CACHE_TTL_MS;
  for (const [key, entry] of captionCache) {
    if (entry.timestamp < cutoff) captionCache.delete(key);
  }
  // Preferred languages first
  for (const lang of preferredLangs) {
    const key = makeCacheKey(videoId, lang);
    const e = captionCache.get(key);
    if (e?.transcript.segments.length) { console.log(`[vas] Cache hit: ${lang}`); return e.transcript; }
  }
  // Fallback: any language for this video
  for (const [k, e] of captionCache) {
    if (k.startsWith(videoId + ":") && e.transcript.segments.length) {
      console.log(`[vas] Cache fallback: ${k}`);
      return e.transcript;
    }
  }
  return null;
}
