/**
 * YouTube 字幕提取器。
 *
 * 从页面中的 ytInitialPlayerResponse 提取字幕轨道信息，
 * 然后 fetch XML 字幕并解析为 [MM:SS] text 格式。
 */

import { UserError } from "../../utils/errors";
import { t } from "../../utils/i18n";
import { getCachedCaptionedText } from "./caption-interceptor";
import type { Transcript, TranscriptSegment } from "../transcript";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
export interface CaptionTrack {
  baseUrl: string;
  name: { simpleText: string };
  vssId: string;
  languageCode: string;
  kind?: string;
}

export interface VideoInfo {
  title: string;
  videoId: string;
  captionTracks: CaptionTrack[];
}

// ---------------------------------------------------------------------------
// Language priority
// ---------------------------------------------------------------------------
const LANG_PRIORITY = ["ja", "en", "zh-Hans", "zh-HK", "zh-TW", "zh"];

// ---------------------------------------------------------------------------
// Extract ytInitialPlayerResponse from page
// ---------------------------------------------------------------------------
function currentUrlVideoId(): string {
  try {
    return new URL(window.location.href).searchParams.get("v") ?? "";
  } catch {
    return "";
  }
}

function playerResponseVideoId(response: Record<string, unknown>): string {
  const details = response.videoDetails as Record<string, unknown> | undefined;
  return typeof details?.videoId === "string" ? details.videoId : "";
}

export function selectPlayerResponseForVideo(
  responses: Record<string, unknown>[],
  expectedVideoId: string,
): Record<string, unknown> | null {
  return responses.find((response) => playerResponseVideoId(response) === expectedVideoId) ?? null;
}

function extractPlayerResponse(expectedVideoId: string): Record<string, unknown> | null {
  if (!expectedVideoId) return null;
  // Method 1: try window.ytInitialPlayerResponse
  const w = window as unknown as Record<string, unknown>;
  if (w.ytInitialPlayerResponse && typeof w.ytInitialPlayerResponse === "object") {
    const response = w.ytInitialPlayerResponse as Record<string, unknown>;
    const matched = selectPlayerResponseForVideo([response], expectedVideoId);
    if (matched) return matched;
  }

  // SPA 页面会保留旧 script；从最新的开始找，并且只接受当前 URL 的视频。
  const scripts = [...document.querySelectorAll("script")].reverse();
  for (const script of scripts) {
    const text = script.textContent ?? "";
    const match = text.match(/var\s+ytInitialPlayerResponse\s*=\s*(\{.+?\});/s);
    if (match) {
      try {
        const response = JSON.parse(match[1]) as Record<string, unknown>;
        const matched = selectPlayerResponseForVideo([response], expectedVideoId);
        if (matched) return matched;
      } catch {
        continue;
      }
    }
    // Also try window.ytInitialPlayerResponse = {...}
    const match2 = text.match(/ytInitialPlayerResponse\s*=\s*(\{.+?\});/s);
    if (match2) {
      try {
        const response = JSON.parse(match2[1]) as Record<string, unknown>;
        const matched = selectPlayerResponseForVideo([response], expectedVideoId);
        if (matched) return matched;
      } catch {
        continue;
      }
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// Parse captions
// ---------------------------------------------------------------------------
function parseCaptionTracks(playerResponse: Record<string, unknown>): CaptionTrack[] {
  const captions = playerResponse?.captions as Record<string, unknown> | undefined;
  const renderer = captions?.playerCaptionsTracklistRenderer as Record<string, unknown> | undefined;
  const tracks = (renderer?.captionTracks as CaptionTrack[]) ?? [];
  return tracks;
}

function pickCaptionTrack(tracks: CaptionTrack[]): CaptionTrack | null {
  if (!tracks.length) return null;

  const byLang = new Map<string, CaptionTrack>();
  for (const t of tracks) {
    if (t.baseUrl && !byLang.has(t.languageCode)) {
      byLang.set(t.languageCode, t);
    }
  }

  for (const lang of LANG_PRIORITY) {
    const match = byLang.get(lang);
    if (match) return match;
  }
  // Fallback: first track with a URL
  return tracks.find((t) => t.baseUrl) ?? null;
}

// ---------------------------------------------------------------------------
// Fetch and parse XML captions
// ---------------------------------------------------------------------------
async function fetchAndParseCaptions(
  baseUrl: string,
  languageCode: string,
  isAutoGenerated: boolean,
): Promise<Transcript> {
  let parsedUrl: URL;
  try {
    parsedUrl = new URL(baseUrl, "https://www.youtube.com");
  } catch {
    throw new UserError(t("errorYoutubeCaptionUnavailable"), "YT_INVALID_CAPTION_URL");
  }
  const isYouTubeHost = parsedUrl.hostname === "youtube.com" ||
    parsedUrl.hostname.endsWith(".youtube.com");
  if (parsedUrl.protocol !== "https:" || !isYouTubeHost) {
    throw new UserError(t("errorYoutubeCaptionUnavailable"), "YT_INVALID_CAPTION_URL");
  }
  // Strip "variant" parameter (e.g., variant=gemini) — it can cause empty
  // responses.  The variant key is NOT in sparams, so removing it does not
  // invalidate the URL signature.
  parsedUrl.searchParams.delete("variant");
  parsedUrl.searchParams.delete("fmt");

  const resp = await fetch(parsedUrl.toString());

  if (!resp.ok) {
    throw new UserError(
      t("errorYoutubeCaptionLoad"),
      "YT_CAPTION_FETCH",
      `HTTP ${resp.status}`,
    );
  }

  const xmlText = await resp.text();

  if (!xmlText || !xmlText.trim()) {
    throw new UserError(
      t("errorYoutubeCaptionUnavailable"),
      "YT_EMPTY_RESPONSE",
    );
  }

  const transcript = parseTimedText(xmlText, languageCode, isAutoGenerated);
  if (!transcript.segments.length) {
    throw new UserError(t("errorYoutubeCaptionUnavailable"), "YT_EMPTY_CAPTIONS");
  }
  return transcript;
}

export function parseTimedText(
  xml: string,
  languageCode: string = "unknown",
  isAutoGenerated: boolean = false,
): Transcript {
  const parser = new DOMParser();
  const doc = parser.parseFromString(xml, "text/xml");
  if (doc.querySelector("parsererror")) {
    return { languageCode, isAutoGenerated, segments: [] };
  }
  const texts = doc.querySelectorAll("text");
  const segments: TranscriptSegment[] = [];
  for (const el of texts) {
    const start = parseFloat(el.getAttribute("start") ?? "0");
    const dur = parseFloat(el.getAttribute("dur") ?? "0");
    if (!Number.isFinite(start) || start < 0 || !Number.isFinite(dur) || dur < 0) continue;
    // YouTube timedtext: content may be in child elements or raw text
    let content = "";
    for (const child of el.children) {
      content += child.textContent ?? "";
    }
    if (!content) {
      content = el.textContent ?? "";
    }
    content = decodeHtmlEntities(content.trim());
    if (content) {
      segments.push({ start, duration: dur, text: content });
    }
  }
  return { languageCode, isAutoGenerated, segments };
}

function decodeHtmlEntities(text: string): string {
  const txt = document.createElement("textarea");
  txt.innerHTML = text;
  return txt.value;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * 提取 INNERTUBE_API_KEY。
 * 尝试多种方式，兼容 YouTube 页面不同的加载状态。
 */
function getApiKey(): string {
  // 方法 1：ytcfg.get()（页面正常加载时可用）
  try {
    const w = window as unknown as { ytcfg?: { get?: (key: string) => unknown; data_?: Record<string, unknown> } };
    const key = w.ytcfg?.get?.("INNERTUBE_API_KEY") as string | undefined;
    if (key) return key;
  } catch { /* continue */ }

  // 方法 2：ytcfg.data_（某些 YouTube 版本）
  try {
    const w = window as unknown as { ytcfg?: { data_?: Record<string, unknown> } };
    const key = w.ytcfg?.data_?.INNERTUBE_API_KEY as string | undefined;
    if (key) return key;
  } catch { /* continue */ }

  // 方法 3：正则提取页面 HTML（youtube-transcript-api 的做法，兼容性最强）
  try {
    const match = document.documentElement.outerHTML.match(
      /"INNERTUBE_API_KEY"\s*:\s*"([a-zA-Z0-9_-]+)"/
    );
    if (match?.[1]) return match[1];
  } catch { /* continue */ }

  return "";
}

/**
 * 通过 InnerTube ANDROID 客户端获取字幕 —— 参考 youtube-transcript-api 方案。
 *
 * YouTube WEB 客户端的 timedtext 请求需要 POT (Proof of Origin Token)，
 * 但 ANDROID 客户端不受此限制。此方法：
 *   1. POST youtubei/v1/player（ANDROID 上下文）→ 获取带有效签名的 baseUrl
 *   2. GET baseUrl → 返回 XML timedtext → 解析
 *
 * 这是目前最可靠的静默字幕获取方式，无需 CC 按钮、拦截器或播放器操作。
 */
async function fetchCaptionsViaInnerTube(
  videoId: string,
): Promise<Transcript> {
  const apiKey = getApiKey();
  if (!apiKey || !videoId) throw new UserError(t("errorPageNotReady"), "YT_NO_API_KEY");

  const resp = await fetch(
    `https://www.youtube.com/youtubei/v1/player?key=${apiKey}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Accept-Language": "en-US",
      },
      body: JSON.stringify({
        context: {
          client: {
            clientName: "ANDROID",
            clientVersion: "20.10.38",
          },
        },
        videoId,
      }),
    },
  );

  if (!resp.ok) throw new UserError(t("errorCaptionService"), "YT_INNERTUBE", `HTTP ${resp.status}`);
  const data = await resp.json();

  const tracks =
    (data?.captions?.playerCaptionsTracklistRenderer
      ?.captionTracks as CaptionTrack[]) ?? [];

  if (!tracks.length) throw new UserError(t("errorNoCaptions"), "YT_NO_CAPTIONS");

  const track = pickCaptionTrack(tracks);
  if (!track) {
    const available = tracks.map((t) => t.languageCode).join(", ");
    throw new UserError(t("errorNoPreferredYoutubeCaptions"), "YT_NO_PREF_LANG", `available: ${available}`);
  }
  return fetchAndParseCaptions(track.baseUrl, track.languageCode, track.kind === "asr");
}

/** 获取当前页面的视频字幕文本。 */
export async function getTranscript(): Promise<Transcript> {
  const videoId = getVideoIdFromUrl();
  if (!videoId) throw new UserError(t("errorNotYoutubeVideo"), "YT_NOT_VIDEO");

  // 1. 无等待快速路径：播放器恰好已经请求过字幕。
  const cached = getCachedCaptionedText(videoId, LANG_PRIORITY);
  if (cached) return cached;

  // 2. 主路径：InnerTube ANDROID（最可靠，静默）
  try {
    const transcript = await fetchCaptionsViaInnerTube(videoId);
    if (getVideoIdFromUrl() !== videoId) throw new DOMException("Navigation changed", "AbortError");
    return transcript;
  } catch (e) {
    if ((e as Error)?.name === "AbortError") throw e;
    console.debug("[vas] InnerTube 失败，回退到直接 fetch:", e instanceof Error ? e.message : String(e));
  }

  // 3. 最终回退：直接 fetch ytInitialPlayerResponse 中的 baseUrl
  const info = getVideoInfo();
  if (!info) throw new UserError(t("errorNotYoutubeVideo"), "YT_NOT_VIDEO");
  if (!info.captionTracks.length) throw new UserError(t("errorNoCaptions"), "YT_NO_CAPTIONS");

  const track = pickCaptionTrack(info.captionTracks);
  if (!track) {
    const available = info.captionTracks.map((t) => t.languageCode).join(", ");
    throw new UserError(t("errorNoPreferredYoutubeCaptions"), "YT_NO_PREF_LANG", `available: ${available}`);
  }

  const transcript = await fetchAndParseCaptions(track.baseUrl, track.languageCode, track.kind === "asr");
  if (getVideoIdFromUrl() !== videoId) throw new DOMException("Navigation changed", "AbortError");
  return transcript;
}

/** 从当前 YouTube 页面提取视频信息（标题 + 字幕轨道）。 */
function getVideoInfo(): VideoInfo | null {
  const videoId = getVideoIdFromUrl();
  const playerResponse = extractPlayerResponse(videoId);
  if (!playerResponse) return null;

  const title = extractTitle(playerResponse);
  const captionTracks = parseCaptionTracks(playerResponse);

  return { title, videoId, captionTracks };
}

/** 从各种来源提取视频 ID。 */
export function getVideoIdFromUrl(): string {
  return currentUrlVideoId();
}

/** 获取当前页面的视频标题（含多重回退）。 */
export function getVideoTitle(): string {
  return extractTitle(extractPlayerResponse(currentUrlVideoId()));
}

/** 检测当前页面是否为 YouTube 视频页。 */
export function isYouTubeVideoPage(): boolean {
  return window.location.pathname === "/watch";
}

// ---------------------------------------------------------------------------
// Internal helpers (used by public API above)
// ---------------------------------------------------------------------------

function extractTitle(playerResponse: Record<string, unknown> | null): string {
  if (playerResponse) {
    const vd = playerResponse.videoDetails as Record<string, unknown> | undefined;
    const title = vd?.title as string | undefined;
    if (title) return title;
  }
  const dt = document.title || "";
  return dt.replace(/\s*-\s*YouTube\s*$/, "").trim() || t("unknownTitle");
}
