import { formatTime } from "../utils/text";
import type { OutputLanguage } from "../utils/i18n";

export interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
}

export interface Transcript {
  languageCode: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
}

export function transcriptToText(transcript: Transcript): string {
  return transcript.segments
    .filter((segment) => segment.text.trim())
    .map((segment) => `${formatTime(segment.start)}\n${segment.text.trim()}`)
    .join("\n");
}

export function isChineseLanguage(languageCode: string): boolean {
  return /^zh(?:-|$)/i.test(languageCode);
}

export function isTranscriptInOutputLanguage(
  languageCode: string,
  outputLanguage: OutputLanguage,
): boolean {
  const normalized = languageCode.trim().toLowerCase().replaceAll("_", "-");
  if (outputLanguage === "zh-CN") {
    return normalized === "zh" || /^zh-(cn|sg|hans)(?:-|$)/.test(normalized);
  }
  if (outputLanguage === "zh-TW") {
    return /^zh-(tw|hk|mo|hant)(?:-|$)/.test(normalized);
  }
  return normalized === outputLanguage || normalized.startsWith(`${outputLanguage}-`);
}
