import { formatTime } from "../utils/text";
import type { OutputLanguage } from "../utils/i18n";

export interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
  /** Exact word/run starts from YouTube JSON3, indexed into normalized `text`. */
  timingMarkers?: TranscriptTimingMarker[];
  /** Inclusive indexes of the original YouTube caption events covered by this cue. */
  sourceStartId?: number;
  sourceEndId?: number;
}

export interface TranscriptTimingMarker {
  offset: number;
  start: number;
}

export interface Transcript {
  languageCode: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
}

const MAX_MERGED_CUE_SECONDS = 8;
const MAX_CONTINUATION_GAP_SECONDS = 0.35;
const MAX_CUE_DISPLAY_WIDTH = 96;
const SENTENCE_END_RE = /[.!?。！？…‥]["'”’）)\]}】」』]*$/u;
const SPEAKER_MARKER_RE = /(?:^|\n)\s*(?:>>|[-–—]\s+|[^\n:]{1,24}:\s)/u;
const CJK_RE = /[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Hangul}]/u;
const LEADING_PUNCTUATION_RE = /^[,.;:!?，。；：！？、…‥）)\]}】」』]/u;

function normalizedText(text: string): string {
  return text
    .split("\n")
    .map((line) => line.trim().replace(/\s+/g, " "))
    .filter(Boolean)
    .join("\n");
}

function displayWidth(text: string): number {
  let width = 0;
  for (const char of text) width += CJK_RE.test(char) ? 2 : 1;
  return width;
}

function joinCueText(left: string, right: string): string {
  if (!left) return right;
  if (!right) return left;
  if (left.endsWith("\n") || right.startsWith("\n")) return `${left}${right}`;
  const last = left.at(-1) ?? "";
  const first = right[0] ?? "";
  const needsSpace = !LEADING_PUNCTUATION_RE.test(right) && !(CJK_RE.test(last) && CJK_RE.test(first));
  return `${left}${needsSpace ? " " : ""}${right}`;
}

function segmentEnd(segment: TranscriptSegment, next?: TranscriptSegment): number {
  if (segment.duration > 0) return segment.start + segment.duration;
  if (next && next.start > segment.start) return Math.min(next.start, segment.start + 2);
  return segment.start + 2;
}

type TimedCaptionAtom = TranscriptSegment & {
  sourceStartId: number;
  sourceEndId: number;
};

interface SentenceFragment {
  text: string;
  offset: number;
}

function splitSentences(text: string, languageCode: string): SentenceFragment[] {
  try {
    const locale = languageCode && languageCode !== "unknown"
      ? languageCode.replaceAll("_", "-")
      : undefined;
    const segmenter = new Intl.Segmenter(locale, { granularity: "sentence" });
    const sentences = Array.from(segmenter.segment(text), ({ segment, index }) => ({
      text: normalizedText(segment),
      offset: index,
    })).filter(({ text: sentence }) => Boolean(sentence));
    return sentences.length ? sentences : [{ text, offset: 0 }];
  } catch {
    // An invalid or uncommon YouTube language tag must not prevent captions rendering.
    return [{ text, offset: 0 }];
  }
}

function exactTimingAtOffset(
  markers: TranscriptTimingMarker[] | undefined,
  offset: number,
): number | null {
  if (!markers?.length) return null;
  let nearest: TranscriptTimingMarker | undefined;
  for (const marker of markers) {
    if (!Number.isFinite(marker.start) || !Number.isInteger(marker.offset)) continue;
    if (!nearest || Math.abs(marker.offset - offset) < Math.abs(nearest.offset - offset)) {
      nearest = marker;
    }
  }
  // Whitespace and punctuation normalization can move a run boundary by a few characters.
  return nearest && Math.abs(nearest.offset - offset) <= 3 ? nearest.start : null;
}

/**
 * A YouTube event may contain the end of one sentence and the start of another.
 * Split that event first, then use exact word timing or a bounded interpolation
 * for boundaries inside its original time span.
 */
function splitTimedCaption(
  segment: TimedCaptionAtom,
  next: TimedCaptionAtom | undefined,
  languageCode: string,
): TimedCaptionAtom[] {
  const sentences = splitSentences(segment.text, languageCode);
  if (sentences.length === 1) return [segment];

  const end = segmentEnd(segment, next);
  const duration = Math.max(0.001, end - segment.start);
  const weights = sentences.map(({ text: sentence }) => Math.max(1, displayWidth(sentence)));
  const totalWeight = weights.reduce((total, weight) => total + weight, 0);
  let elapsedWeight = 0;
  let previousStart = segment.start;
  const starts: number[] = [];

  for (const [index, { offset }] of sentences.entries()) {
    const estimatedStart = segment.start + duration * (elapsedWeight / totalWeight);
    const markerStart = index > 0 ? exactTimingAtOffset(segment.timingMarkers, offset) : null;
    const latestStart = end - (sentences.length - index) * 0.001;
    const start = index === 0
      ? segment.start
      : Math.min(latestStart, Math.max(previousStart + 0.001, markerStart ?? estimatedStart));
    starts.push(start);
    previousStart = start;
    elapsedWeight += weights[index];
  }

  return sentences.map(({ text: sentence }, index) => {
    const start = starts[index];
    return {
      start,
      duration: Math.max(0.001, (starts[index + 1] ?? end) - start),
      text: sentence,
      sourceStartId: segment.sourceStartId,
      sourceEndId: segment.sourceEndId,
    };
  });
}

/**
 * Build stable, player-safe caption cues without asking the model to invent timing.
 * Sentence boundaries inside YouTube events are interpolated locally, then fragments
 * that continue across adjacent events are merged back into complete utterances.
 */
export function buildAlignedTranscript(transcript: Transcript): Transcript {
  const source = transcript.segments
    .map((segment, sourceId) => ({
      ...segment,
      text: normalizedText(segment.text),
      sourceStartId: segment.sourceStartId ?? sourceId,
      sourceEndId: segment.sourceEndId ?? sourceId,
    }))
    .filter((segment) => segment.text);
  const atoms = source.flatMap((segment, index) => (
    splitTimedCaption(segment, source[index + 1], transcript.languageCode)
  ));
  const segments: TranscriptSegment[] = [];

  for (let index = 0; index < atoms.length;) {
    const first = atoms[index];
    let lastIndex = index;
    let text = first.text;
    let end = segmentEnd(first, atoms[index + 1]);

    while (lastIndex + 1 < atoms.length) {
      const current = atoms[lastIndex];
      const next = atoms[lastIndex + 1];
      const gap = next.start - segmentEnd(current, next);
      const combinedText = joinCueText(text, next.text);
      const combinedEnd = segmentEnd(next, atoms[lastIndex + 2]);
      const combinedDuration = Math.max(0, combinedEnd - first.start);
      const hasHardBoundary =
        SENTENCE_END_RE.test(text.trim()) ||
        text.includes("\n") ||
        next.text.includes("\n") ||
        SPEAKER_MARKER_RE.test(next.text) ||
        gap > MAX_CONTINUATION_GAP_SECONDS;
      if (
        hasHardBoundary ||
        combinedDuration > MAX_MERGED_CUE_SECONDS ||
        displayWidth(combinedText) > MAX_CUE_DISPLAY_WIDTH
      ) break;

      lastIndex += 1;
      text = combinedText;
      end = combinedEnd;
    }

    const last = atoms[lastIndex];
    segments.push({
      start: first.start,
      duration: Math.max(0.1, Math.round((end - first.start) * 1000) / 1000),
      text,
      sourceStartId: first.sourceStartId,
      sourceEndId: last.sourceEndId,
    });
    index = lastIndex + 1;
  }

  return { ...transcript, segments };
}

/** Locate the cue active at the given playback time. */
export function findActiveCueIndex(segments: TranscriptSegment[], time: number): number {
  let low = 0;
  let high = segments.length - 1;
  let candidate = -1;
  while (low <= high) {
    const middle = Math.floor((low + high) / 2);
    if (segments[middle].start <= time) {
      candidate = middle;
      low = middle + 1;
    } else {
      high = middle - 1;
    }
  }
  if (candidate < 0) return -1;
  const cue = segments[candidate];
  return time < cue.start + cue.duration ? candidate : -1;
}

export interface CaptionPrefetchRange {
  start: number;
  end: number;
}

/** Calculate the next missing cue window without introducing playback side effects. */
export function getCaptionPrefetchRange(
  segments: TranscriptSegment[],
  currentCueId: number,
  currentTime: number,
  hasTranslation: (cueId: number) => boolean,
  minimumBufferSeconds: number = 15,
  windowSeconds: number = 60,
): CaptionPrefetchRange | null {
  let firstMissing = currentCueId;
  while (firstMissing < segments.length && hasTranslation(firstMissing)) firstMissing += 1;
  if (firstMissing >= segments.length) return null;
  const bufferedEnd = firstMissing > currentCueId
    ? segments[firstMissing - 1].start + segments[firstMissing - 1].duration
    : segments[currentCueId]?.start ?? currentTime;
  if (firstMissing > currentCueId && bufferedEnd - currentTime >= minimumBufferSeconds) {
    return null;
  }

  const startTime = segments[firstMissing].start;
  let end = firstMissing;
  while (end + 1 < segments.length && segments[end + 1].start < startTime + windowSeconds) {
    end += 1;
  }
  return { start: firstMissing, end };
}

export function transcriptToText(transcript: Transcript): string {
  return transcript.segments
    .filter((segment) => segment.text.trim())
    .map((segment) => `${formatTime(segment.start)}\n${segment.text.trim()}`)
    .join("\n");
}

export function isTranscriptInOutputLanguage(
  languageCode: string,
  outputLanguage: OutputLanguage,
): boolean {
  const normalized = languageCode.trim().toLowerCase().replaceAll("_", "-");
  if (outputLanguage === "zh-CN") {
    return normalized === "zh" || /^zh-(cn|sg|hans)(?:-|$)/.test(normalized);
  }
  if (outputLanguage === "zh-TW") {
    return /^zh-(tw|hk|mo|hant)(?:-|$)/.test(normalized);
  }
  return normalized === outputLanguage || normalized.startsWith(`${outputLanguage}-`);
}
