import { describe, expect, it } from "vitest";
import {
  buildAlignedTranscript,
  findActiveCueIndex,
  getCaptionPrefetchRange,
  isTranscriptInOutputLanguage,
  transcriptToText,
  type Transcript,
} from "./transcript";
import {
  isTranslatedCaptionURL,
  parseJson3Captions,
} from "./extractors/caption-interceptor";

describe("transcript helpers", () => {
  it("matches source captions to output languages and distinguishes Chinese scripts", () => {
    expect(isTranscriptInOutputLanguage("en-US", "en")).toBe(true);
    expect(isTranscriptInOutputLanguage("ja", "ja")).toBe(true);
    expect(isTranscriptInOutputLanguage("zh-Hans", "zh-CN")).toBe(true);
    expect(isTranscriptInOutputLanguage("zh-TW", "zh-TW")).toBe(true);
    expect(isTranscriptInOutputLanguage("zh-TW", "zh-CN")).toBe(false);
    expect(isTranscriptInOutputLanguage("zh", "zh-TW")).toBe(false);
  });

  it("converts structured segments to the legacy timestamp format", () => {
    const transcript: Transcript = {
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 1.9, duration: 2, text: " Hello " },
        { start: 61, duration: 2, text: "world" },
      ],
    };
    expect(transcriptToText(transcript)).toBe("0:01\nHello\n1:01\nworld");
  });

  it("caps player prefetch by both time and characters", () => {
    const segments = [
      { start: 0, duration: 10, text: "a".repeat(20) },
      { start: 10, duration: 10, text: "b".repeat(20) },
      { start: 20, duration: 10, text: "c".repeat(20) },
      { start: 30, duration: 10, text: "d".repeat(20) },
    ];
    expect(getCaptionPrefetchRange(segments, 0, 0, () => false, 15, 120, 90))
      .toEqual({ start: 0, end: 1 });
    expect(getCaptionPrefetchRange(segments, 0, 0, () => false, 15, 30, 10_000))
      .toEqual({ start: 0, end: 2 });
  });

  it("merges only short continuing fragments and preserves source ranges", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 0, duration: 0.8, text: "I" },
        { start: 0.9, duration: 0.8, text: "think" },
        { start: 1.8, duration: 0.8, text: "so." },
        { start: 3, duration: 0.7, text: "Yes." },
      ],
    });

    expect(aligned.segments.map(({
      start,
      duration,
      text,
      sourceStartId,
      sourceEndId,
    }) => ({ start, duration, text, sourceStartId, sourceEndId }))).toEqual([
      {
        start: 0,
        duration: 2.6,
        text: "I think so.",
        sourceStartId: 0,
        sourceEndId: 2,
      },
      {
        start: 3,
        duration: 0.7,
        text: "Yes.",
        sourceStartId: 3,
        sourceEndId: 3,
      },
    ]);
  });

  it("keeps dialogue and sufficiently long YouTube cues separate", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 178, duration: 6, text: "had attempted it and not finished because it's a brutal event." },
        { start: 184, duration: 6, text: "One of the best things about doing the race is afterwards you finish." },
        { start: 190.1, duration: 1, text: ">> Host: Exactly." },
      ],
    });

    expect(aligned.segments.map(({ start, text, sourceStartId, sourceEndId }) => ({
      start,
      text,
      sourceStartId,
      sourceEndId,
    }))).toEqual([
      {
        start: 178,
        text: "had attempted it and not finished because it's a brutal event.",
        sourceStartId: 0,
        sourceEndId: 0,
      },
      {
        start: 184,
        text: "One of the best things about doing the race is afterwards you finish.",
        sourceStartId: 1,
        sourceEndId: 1,
      },
      {
        start: 190.1,
        text: ">> Host: Exactly.",
        sourceStartId: 2,
        sourceEndId: 2,
      },
    ]);
  });

  it("reconstructs sentences that end and restart inside adjacent YouTube cues", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 0, duration: 3, text: "a lot of concern about the issues of" },
        { start: 3, duration: 3, text: "affordability. Your feeling is not wrong" },
        { start: 6, duration: 3, text: "in the data. And kind of the question" },
        { start: 9, duration: 3, text: "there is why haven't wages kept up with" },
        { start: 12, duration: 3, text: "the cost of living? It can get complicated." },
      ],
    });

    expect(aligned.segments.map(({ text }) => text)).toEqual([
      "a lot of concern about the issues of affordability.",
      "Your feeling is not wrong in the data.",
      "And kind of the question there is why haven't wages kept up with the cost of living?",
      "It can get complicated.",
    ]);
    expect(aligned.segments[0].sourceStartId).toBe(0);
    expect(aligned.segments[0].sourceEndId).toBe(1);
    expect(aligned.segments[1].start).toBeGreaterThan(3);
    expect(aligned.segments[1].start).toBeLessThan(6);
    expect(aligned.segments[1].sourceStartId).toBe(1);
    expect(aligned.segments[1].sourceEndId).toBe(2);
  });

  it("uses an exact JSON3 word boundary instead of proportional sentence timing", async () => {
    const text = "This first sentence takes a while. Next sentence starts quickly.";
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [{
        start: 100,
        duration: 8,
        text,
        timingMarkers: [
          { offset: 0, start: 100 },
          { offset: text.indexOf("Next"), start: 102.25 },
        ],
      }],
    });

    expect(aligned.segments.map(({ start, text: cueText }) => ({ start, text: cueText })))
      .toEqual([
        { start: 100, text: "This first sentence takes a while." },
        { start: 102.25, text: "Next sentence starts quickly." },
      ]);
  });

  it("does not treat source cue edges after conjunctions and prepositions as sentences", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 0, duration: 2, text: "We wanted to go and" },
        { start: 2, duration: 2, text: "finish the work because" },
        { start: 4, duration: 2, text: "of the deadline." },
      ],
    });

    expect(aligned.segments.map(({ text }) => text)).toEqual([
      "We wanted to go and finish the work because of the deadline.",
    ]);
  });

  it("keeps abbreviations and unclosed quotes attached to their continuation", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 0, duration: 1, text: "Dr." },
        { start: 1, duration: 8, text: "Smith said \"this is" },
        { start: 9, duration: 8, text: "still one sentence.\" Then left." },
      ],
    });

    expect(aligned.segments.map(({ text }) => text)).toEqual([
      "Dr. Smith said \"this is still one sentence.\"",
      "Then left.",
    ]);
  });

  it("soft-splits an oversized open quote instead of allowing an unbounded cue", async () => {
    const quotedSpeech = `"${Array.from({ length: 160 }, () => "word").join(" ")}."`;
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [{
        start: 0,
        duration: 30,
        text: `${quotedSpeech} Afterwards we stopped.`,
      }],
    });

    expect(aligned.segments.length).toBeGreaterThan(2);
    expect(aligned.segments.map(({ text }) => text).join(" ")).toBe(
      `${quotedSpeech} Afterwards we stopped.`,
    );
    expect(aligned.segments.every(({ text }) => text.length <= 200)).toBe(true);
    expect(aligned.segments.at(-1)?.text).toBe("Afterwards we stopped.");
  });

  it("splits a long appositive caption at its explanatory comma", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [{
        start: 0,
        duration: 8,
        text: "It's called a microcontroller, a little computer that you can program to do certain things with sensors and actuators and stuff like that attached.",
      }],
    });

    expect(aligned.segments.map(({ text, splitReason }) => ({ text, splitReason }))).toEqual([
      {
        text: "It's called a microcontroller,",
        splitReason: "clause-boundary",
      },
      {
        text: "a little computer that you can program to do certain things with sensors and actuators and stuff like that attached.",
        splitReason: "end-of-transcript",
      },
    ]);
  });

  it("allows sentence boundaries inside a long unmatched quotation", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [{
        start: 0,
        duration: 46,
        text: "\"Well, if you sell your US treasuries in like a fire sale type of situation, then the price of US treasuries is going to plummet. It's going to fall and then interest rates in America will shoot up because US treasuries, you know, which are like IUS, they have an inverse relationship. So if the price of the bonds goes down, then the interest rate is going to go up. So, this chart, it's showing the interest rate on a 30-year US Treasury bond. I mean, the yield, the interest rates going up because the price of the bonds have been going down. And Bessant is like, \"Listen,",
      }],
    });

    expect(aligned.segments.map(({ text }) => text)).toEqual([
      "\"Well, if you sell your US treasuries in like a fire sale type of situation, then the price of US treasuries is going to plummet.",
      "It's going to fall and then interest rates in America will shoot up because US treasuries, you know,",
      "which are like IUS, they have an inverse relationship.",
      "So if the price of the bonds goes down, then the interest rate is going to go up.",
      "So, this chart, it's showing the interest rate on a 30-year US Treasury bond.",
      "I mean, the yield, the interest rates going up because the price of the bonds have been going down.",
      "And Bessant is like, \"Listen,",
    ]);
  });

  it("prefers a clause boundary over splitting a verb from its complement", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [{
        start: 0,
        duration: 20,
        text: "Nuclear construction gets easier, or I should probably say any construction gets easier when you stop treating every reactor as a custombuilt architectural masterpiece and start treating it like an industrial product.",
      }],
    });

    expect(aligned.segments.map(({ text }) => text)).toEqual([
      "Nuclear construction gets easier, or I should probably say any construction gets easier",
      "when you stop treating every reactor as a custombuilt architectural masterpiece and start treating it like an industrial product.",
    ]);
    expect(aligned.segments.some(({ text }) => /\bstop$/iu.test(text))).toBe(false);
  });

  it("hides known sound labels and keeps contractions attached to their predicates", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [{
        start: 0,
        duration: 16,
        text: "[Music] the web's transformed culture it's transformed the way we do Commerce it's transformed the way we do advertising it's",
      }],
    });

    expect(aligned.segments.map(({ text }) => text)).toEqual([
      "the web's transformed culture it's transformed the way we do Commerce",
      "it's transformed the way we do advertising it's",
    ]);
    expect(aligned.segments.every(({ text }) => !/\[Music\]/iu.test(text))).toBe(true);
    expect(aligned.segments.slice(0, -1).every(({ text }) => !/\bit['’]s$/iu.test(text))).toBe(true);

    const meaningfulBrackets = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: false,
      segments: [{ start: 0, duration: 2, text: "[NASA] mission control." }],
    });
    expect(meaningfulBrackets.segments.map(({ text }) => text)).toEqual([
      "[NASA] mission control.",
    ]);
  });

  it("uses a real long pause as a semantic boundary without filling the gap", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 0, duration: 1, text: "First thought" },
        { start: 1.8, duration: 1, text: "Second thought" },
      ],
    });

    expect(aligned.segments.map(({ start, duration, text, splitReason }) => ({
      start,
      duration,
      text,
      splitReason,
    }))).toEqual([
      {
        start: 0,
        duration: 1,
        text: "First thought",
        splitReason: "long-pause",
      },
      {
        start: 1.8,
        duration: 1,
        text: "Second thought",
        splitReason: "end-of-transcript",
      },
    ]);
    expect(findActiveCueIndex(aligned.segments, 1.4)).toBe(-1);
  });

  it("treats a comma plus medium pause as a candidate, not an automatic cut", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 0, duration: 1, text: "We tried," },
        { start: 1.35, duration: 1.5, text: "but the same sentence continued." },
      ],
    });

    expect(aligned.segments.map(({ text }) => text)).toEqual([
      "We tried, but the same sentence continued.",
    ]);
  });

  it("does not cut a CJK sentence after a grammatical particle", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "ja",
      isAutoGenerated: true,
      segments: [
        { start: 0, duration: 2, text: "これは私たちの" },
        { start: 2, duration: 4, text: "重要な計画です。次に進みます。" },
      ],
    });

    expect(aligned.segments.map(({ text }) => text)).toEqual([
      "これは私たちの重要な計画です。",
      "次に進みます。",
    ]);
  });

  it("soft-splits oversized unpunctuated speech at a non-forbidden candidate", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 0, duration: 3, text: "We started with the background and" },
        { start: 3, duration: 3, text: "carefully reviewed every available measurement before" },
        { start: 6, duration: 3, text: "the engineering group compared all proposed alternatives and" },
        { start: 9, duration: 3, text: "documented the important tradeoffs for everyone involved" },
        { start: 12, duration: 3, text: "then the final review continued with additional evidence" },
        { start: 15, duration: 3, text: "from several independent experiments across the organization" },
      ],
    });

    expect(aligned.segments.length).toBeGreaterThan(1);
    expect(aligned.segments.slice(0, -1).every(({ text }) => (
      !/\b(?:and|before|from|the|with)$/iu.test(text)
    ))).toBe(true);
    expect(aligned.segments.some(({ splitReason }) => (
      splitReason === "forced-best-candidate"
    ))).toBe(true);
  });

  it("finds active cues without filling real caption gaps", () => {
    const segments = [
      { start: 0, duration: 2, text: "zero" },
      { start: 4, duration: 2, text: "four" },
    ];
    expect(findActiveCueIndex(segments, 1.99)).toBe(0);
    expect(findActiveCueIndex(segments, 3)).toBe(-1);
    expect(findActiveCueIndex(segments, 4)).toBe(1);
    expect(findActiveCueIndex(segments, 6)).toBe(-1);
  });

  it("bounds zero-duration caption fallbacks instead of filling long gaps", async () => {
    const aligned = await buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 0, duration: 0, text: "brief" },
        { start: 10, duration: 2, text: "later" },
      ],
    });
    expect(aligned.segments[0].duration).toBe(2);
    expect(findActiveCueIndex(aligned.segments, 5)).toBe(-1);
  });

  it("prefetches 60 seconds from the first missing cue once buffer is low", () => {
    const segments = Array.from({ length: 20 }, (_, index) => ({
      start: index * 5,
      duration: 5,
      text: String(index),
    }));
    const translated = new Set([4, 5, 6, 7]);

    expect(getCaptionPrefetchRange(
      segments,
      4,
      21,
      (cueId) => translated.has(cueId),
    )).toBeNull();
    expect(getCaptionPrefetchRange(
      segments,
      6,
      34,
      (cueId) => translated.has(cueId),
    )).toEqual({ start: 8, end: 19 });
  });
});

describe("YouTube JSON3 caption parsing", () => {
  it("rejects YouTube auto-translation requests as source-caption candidates", () => {
    expect(isTranslatedCaptionURL(
      "https://www.youtube.com/api/timedtext?v=video&lang=en&tlang=zh-Hans",
    )).toBe(true);
    expect(isTranslatedCaptionURL(
      "https://www.youtube.com/api/timedtext?v=video&lang=en",
    )).toBe(false);
  });

  it("preserves start time, duration, language, and text", () => {
    const parsed = parseJson3Captions(JSON.stringify({
      events: [
        {
          tStartMs: 1250,
          dDurationMs: 2750,
          segs: [{ utf8: "hello " }, { utf8: "world" }],
        },
      ],
    }), "en");

    expect(parsed).toEqual({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 1.25, duration: 2.75, text: "hello world" },
      ],
    });
  });

  it("preserves exact per-run offsets for sentence timing", () => {
    const parsed = parseJson3Captions(JSON.stringify({
      events: [{
        tStartMs: 700_000,
        dDurationMs: 6_000,
        segs: [
          { utf8: "Previous sentence. ", tOffsetMs: 0 },
          { utf8: "And", tOffsetMs: 1_750 },
          { utf8: " now the next sentence.", tOffsetMs: 1_950 },
        ],
      }],
    }), "en");

    expect(parsed?.segments[0]).toEqual({
      start: 700,
      duration: 6,
      text: "Previous sentence. And now the next sentence.",
      timingMarkers: [
        { offset: 0, start: 700 },
        { offset: 19, start: 701.75 },
        { offset: 23, start: 701.95 },
      ],
    });
  });
});
