import { describe, expect, it } from "vitest";
import {
  buildAlignedTranscript,
  findActiveCueIndex,
  getCaptionPrefetchRange,
  isTranscriptInOutputLanguage,
  transcriptToText,
  type Transcript,
} from "./transcript";
import {
  isTranslatedCaptionURL,
  parseJson3Captions,
} from "./extractors/caption-interceptor";

describe("transcript helpers", () => {
  it("matches source captions to output languages and distinguishes Chinese scripts", () => {
    expect(isTranscriptInOutputLanguage("en-US", "en")).toBe(true);
    expect(isTranscriptInOutputLanguage("ja", "ja")).toBe(true);
    expect(isTranscriptInOutputLanguage("zh-Hans", "zh-CN")).toBe(true);
    expect(isTranscriptInOutputLanguage("zh-TW", "zh-TW")).toBe(true);
    expect(isTranscriptInOutputLanguage("zh-TW", "zh-CN")).toBe(false);
    expect(isTranscriptInOutputLanguage("zh", "zh-TW")).toBe(false);
  });

  it("converts structured segments to the legacy timestamp format", () => {
    const transcript: Transcript = {
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 1.9, duration: 2, text: " Hello " },
        { start: 61, duration: 2, text: "world" },
      ],
    };
    expect(transcriptToText(transcript)).toBe("0:01\nHello\n1:01\nworld");
  });

  it("merges only short continuing fragments and preserves source ranges", () => {
    const aligned = buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 0, duration: 0.8, text: "I" },
        { start: 0.9, duration: 0.8, text: "think" },
        { start: 1.8, duration: 0.8, text: "so." },
        { start: 3, duration: 0.7, text: "Yes." },
      ],
    });

    expect(aligned.segments).toEqual([
      {
        start: 0,
        duration: 2.6,
        text: "I think so.",
        sourceStartId: 0,
        sourceEndId: 2,
      },
      {
        start: 3,
        duration: 0.7,
        text: "Yes.",
        sourceStartId: 3,
        sourceEndId: 3,
      },
    ]);
  });

  it("keeps dialogue and sufficiently long YouTube cues separate", () => {
    const aligned = buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 178, duration: 6, text: "had attempted it and not finished because it's a brutal event." },
        { start: 184, duration: 6, text: "One of the best things about doing the race is afterwards you finish." },
        { start: 190.1, duration: 1, text: ">> Host: Exactly." },
      ],
    });

    expect(aligned.segments.map(({ start, text, sourceStartId, sourceEndId }) => ({
      start,
      text,
      sourceStartId,
      sourceEndId,
    }))).toEqual([
      {
        start: 178,
        text: "had attempted it and not finished because it's a brutal event.",
        sourceStartId: 0,
        sourceEndId: 0,
      },
      {
        start: 184,
        text: "One of the best things about doing the race is afterwards you finish.",
        sourceStartId: 1,
        sourceEndId: 1,
      },
      {
        start: 190.1,
        text: ">> Host: Exactly.",
        sourceStartId: 2,
        sourceEndId: 2,
      },
    ]);
  });

  it("reconstructs sentences that end and restart inside adjacent YouTube cues", () => {
    const aligned = buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 0, duration: 3, text: "a lot of concern about the issues of" },
        { start: 3, duration: 3, text: "affordability. Your feeling is not wrong" },
        { start: 6, duration: 3, text: "in the data. And kind of the question" },
        { start: 9, duration: 3, text: "there is why haven't wages kept up with" },
        { start: 12, duration: 3, text: "the cost of living? It can get complicated." },
      ],
    });

    expect(aligned.segments.map(({ text }) => text)).toEqual([
      "a lot of concern about the issues of affordability.",
      "Your feeling is not wrong in the data.",
      "And kind of the question there is why haven't wages kept up with the cost of living?",
      "It can get complicated.",
    ]);
    expect(aligned.segments[0].sourceStartId).toBe(0);
    expect(aligned.segments[0].sourceEndId).toBe(1);
    expect(aligned.segments[1].start).toBeGreaterThan(3);
    expect(aligned.segments[1].start).toBeLessThan(6);
    expect(aligned.segments[1].sourceStartId).toBe(1);
    expect(aligned.segments[1].sourceEndId).toBe(2);
  });

  it("uses an exact JSON3 word boundary instead of proportional sentence timing", () => {
    const text = "This first sentence takes a while. Next sentence starts quickly.";
    const aligned = buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [{
        start: 100,
        duration: 8,
        text,
        timingMarkers: [
          { offset: 0, start: 100 },
          { offset: text.indexOf("Next"), start: 102.25 },
        ],
      }],
    });

    expect(aligned.segments.map(({ start, text: cueText }) => ({ start, text: cueText })))
      .toEqual([
        { start: 100, text: "This first sentence takes a while." },
        { start: 102.25, text: "Next sentence starts quickly." },
      ]);
  });

  it("finds active cues without filling real caption gaps", () => {
    const segments = [
      { start: 0, duration: 2, text: "zero" },
      { start: 4, duration: 2, text: "four" },
    ];
    expect(findActiveCueIndex(segments, 1.99)).toBe(0);
    expect(findActiveCueIndex(segments, 3)).toBe(-1);
    expect(findActiveCueIndex(segments, 4)).toBe(1);
    expect(findActiveCueIndex(segments, 6)).toBe(-1);
  });

  it("bounds zero-duration caption fallbacks instead of filling long gaps", () => {
    const aligned = buildAlignedTranscript({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 0, duration: 0, text: "brief" },
        { start: 10, duration: 2, text: "later" },
      ],
    });
    expect(aligned.segments[0].duration).toBe(2);
    expect(findActiveCueIndex(aligned.segments, 5)).toBe(-1);
  });

  it("prefetches 60 seconds from the first missing cue once buffer is low", () => {
    const segments = Array.from({ length: 20 }, (_, index) => ({
      start: index * 5,
      duration: 5,
      text: String(index),
    }));
    const translated = new Set([4, 5, 6, 7]);

    expect(getCaptionPrefetchRange(
      segments,
      4,
      21,
      (cueId) => translated.has(cueId),
    )).toBeNull();
    expect(getCaptionPrefetchRange(
      segments,
      6,
      34,
      (cueId) => translated.has(cueId),
    )).toEqual({ start: 8, end: 19 });
  });
});

describe("YouTube JSON3 caption parsing", () => {
  it("rejects YouTube auto-translation requests as source-caption candidates", () => {
    expect(isTranslatedCaptionURL(
      "https://www.youtube.com/api/timedtext?v=video&lang=en&tlang=zh-Hans",
    )).toBe(true);
    expect(isTranslatedCaptionURL(
      "https://www.youtube.com/api/timedtext?v=video&lang=en",
    )).toBe(false);
  });

  it("preserves start time, duration, language, and text", () => {
    const parsed = parseJson3Captions(JSON.stringify({
      events: [
        {
          tStartMs: 1250,
          dDurationMs: 2750,
          segs: [{ utf8: "hello " }, { utf8: "world" }],
        },
      ],
    }), "en");

    expect(parsed).toEqual({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 1.25, duration: 2.75, text: "hello world" },
      ],
    });
  });

  it("preserves exact per-run offsets for sentence timing", () => {
    const parsed = parseJson3Captions(JSON.stringify({
      events: [{
        tStartMs: 700_000,
        dDurationMs: 6_000,
        segs: [
          { utf8: "Previous sentence. ", tOffsetMs: 0 },
          { utf8: "And", tOffsetMs: 1_750 },
          { utf8: " now the next sentence.", tOffsetMs: 1_950 },
        ],
      }],
    }), "en");

    expect(parsed?.segments[0]).toEqual({
      start: 700,
      duration: 6,
      text: "Previous sentence. And now the next sentence.",
      timingMarkers: [
        { offset: 0, start: 700 },
        { offset: 19, start: 701.75 },
        { offset: 23, start: 701.95 },
      ],
    });
  });
});
