import { formatTime } from "../utils/text";

export interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
}

export interface Transcript {
  languageCode: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
}

export function transcriptToText(transcript: Transcript): string {
  return transcript.segments
    .filter((segment) => segment.text.trim())
    .map((segment) => `${formatTime(segment.start)}\n${segment.text.trim()}`)
    .join("\n");
}

export function isChineseLanguage(languageCode: string): boolean {
  return /^zh(?:-|$)/i.test(languageCode);
}
