import { describe, expect, it } from "vitest";
import {
  isChineseLanguage,
  isTranscriptInOutputLanguage,
  transcriptToText,
  type Transcript,
} from "./transcript";
import { parseJson3Captions } from "./extractors/caption-interceptor";

describe("transcript helpers", () => {
  it("recognizes YouTube Chinese language variants", () => {
    expect(isChineseLanguage("zh")).toBe(true);
    expect(isChineseLanguage("zh-Hans")).toBe(true);
    expect(isChineseLanguage("zh-TW")).toBe(true);
    expect(isChineseLanguage("en")).toBe(false);
    expect(isChineseLanguage("ja")).toBe(false);
  });

  it("matches source captions to output languages and distinguishes Chinese scripts", () => {
    expect(isTranscriptInOutputLanguage("en-US", "en")).toBe(true);
    expect(isTranscriptInOutputLanguage("ja", "ja")).toBe(true);
    expect(isTranscriptInOutputLanguage("zh-Hans", "zh-CN")).toBe(true);
    expect(isTranscriptInOutputLanguage("zh-TW", "zh-TW")).toBe(true);
    expect(isTranscriptInOutputLanguage("zh-TW", "zh-CN")).toBe(false);
    expect(isTranscriptInOutputLanguage("zh", "zh-TW")).toBe(false);
  });

  it("converts structured segments to the legacy timestamp format", () => {
    const transcript: Transcript = {
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 1.9, duration: 2, text: " Hello " },
        { start: 61, duration: 2, text: "world" },
      ],
    };
    expect(transcriptToText(transcript)).toBe("0:01\nHello\n1:01\nworld");
  });
});

describe("YouTube JSON3 caption parsing", () => {
  it("preserves start time, duration, language, and text", () => {
    const parsed = parseJson3Captions(JSON.stringify({
      events: [
        {
          tStartMs: 1250,
          dDurationMs: 2750,
          segs: [{ utf8: "hello " }, { utf8: "world" }],
        },
      ],
    }), "en");

    expect(parsed).toEqual({
      languageCode: "en",
      isAutoGenerated: true,
      segments: [
        { start: 1.25, duration: 2.75, text: "hello world" },
      ],
    });
  });
});
